version: '3'
services:
  node:
    build: .
    ports:
      - 3000:3000
    volumes:
      - ./app:/stickerum
      - /stickerum/node_modules
    links:
      - mongo
      - redis
    depends_on:
      - mongo
      - redis

  mongo:
    image: mongo:latest
    ports:
      - 27017:27017

  redis:
    image: redis:latest
    ports:
      - 6379:6379
