plugins:
  # Consumes files by @import rule
  # https://github.com/postcss/postcss-import
  postcss-import: {}

  # Convert modern CSS into something most browsers can understand
  # https://github.com/csstools/postcss-preset-env
  postcss-preset-env:
    # Polyfill CSS features
    # https://github.com/csstools/postcss-preset-env#stage
    #
    # List of features with levels: https://cssdb.org/
    stage: 0

    # Define polyfills based on browsers you are supporting
    # https://github.com/csstools/postcss-preset-env#browsers
    browsers:
      - 'last 2 versions'
      - '> 1%'

    # Instruct all plugins to omit pre-polyfilled CSS
    # https://github.com/csstools/postcss-preset-env#preserve
    preserve: false

    # Enable or disable specific polyfills
    # https://github.com/csstools/postcss-preset-env#features
    features:
      # Disable polyfilling double-position gradients in CSS
      # https://cssdb.org/#double-position-gradients
      # https://github.com/jonathantneal/postcss-double-position-gradients
      #
      # Solves problems with radial-gradient
      # https://github.com/csstools/postcss-preset-env/issues/120
      double-position-gradients: false

      # Custom values
      # https://cssdb.org/#custom-properties
      # https://github.com/postcss/postcss-custom-properties
      custom-properties:
        # Where Custom Properties can be imported from
        # https://github.com/postcss/postcss-custom-properties#importfrom
        importFrom: './frontend/css/_variables.css'

      # Aliases that represent media queries
      # https://cssdb.org/#custom-media-queries
      # https://github.com/postcss/postcss-custom-media
      custom-media-queries:
        # Where custom media can be imported from
        # https://github.com/postcss/postcss-custom-media#importfrom
        importFrom: './frontend/css/_media-queries.css'

  # Nested rules unwrapper
  # https://github.com/postcss/postcss-nested
  #
  # As you know 'postcss-preset-env' plugin has an ability to process
  # 'postcss-nesting' feature but it does not work with BEM
  # Report: https://github.com/csstools/postcss-preset-env/issues/40
  postcss-nested: {}

  # Font loader
  # https://github.com/jonathantneal/postcss-font-magician
  postcss-font-magician: {}

  # Reference an SVG file and control its attributes
  # https://github.com/TrySound/postcss-inline-svg
  postcss-inline-svg: {}

  # Compression tool
  # https://github.com/cssnano/cssnano
  cssnano: {}
